### PR TITLE
Update ci

### PR DESCRIPTION
**Pull request by zancas**

### CODE REVIEW

**Comment by AloeareV** [comment]
Fixes #97

**Review by AloeareV — DISMISSED** [review]
Looks good. The runtime of >1h is a concern. I'm approving this, but will wait for @zancas to merge, as I'd like to see the runtime cut down somehow, possibly with some sort of cache. I don't think GH caches are large enough, but maybe the dockerfile could be split into more digestible pieces and uploaded somewhere? So that only parts of it need to be rebuilt, depending on what's changed. 

I don't consider this to be a blocking concern, but if this is something that could be done with a small amount of further work it would make sense to put it in this PR.

**Comment by juanky201271** [comment]
Another thing is: The app have two kinds of buildings, one for Android and one for IOS... Maybe we need both in CI.

**Comment by zancas** [comment]
I will mark this DRAFT...  until I can get back to it.

**Comment by zancas** [comment]
@juanky201271 is this totally obsolete?

**Comment by zancas** [comment]
@Oscar-Pepper probably the only piece of this worth saving is the `ci.yml`...   maybe take a look at it, and then probably close this PR in favor of something more up-to-date?

**Comment by juanky201271** [comment]
> @juanky201271 is this totally obsolete?

It's old, but I don't know if obsolete.... maybe not.

**Comment by Oscar-Pepper** [comment]
> @Oscar-Pepper probably the only piece of this worth saving is the `ci.yml`... maybe take a look at it, and then probably close this PR in favor of something more up-to-date?

yes sure, im not too familiar with the zingo-mobile codebase yet so not sure about the other files but for the ci.yml we can pull through the build job into the new CI setup.

i will close now, we can always refer back to this in the future if needs be

**Comment by Oscar-Pepper** [comment]
continued in #137

**Pull request closed without merging**
