### PR TITLE
update CI 2.0

### LINKED ISSUE #97: build.rs needs to run as part of PR automated checks

### PR DESCRIPTION
**Pull request by Oscar-Pepper**
testing CI without docker://node

### CODE REVIEW

**Comment by Oscar-Pepper** [comment]
changes: 
- added **Build** job
- now enables CI for draft PRs and pushes to main/dev branches
- changes runner to ubuntu-22.04 in case CI breaks when github updates latest version
- removed docker://node:latest (any comments welcome!)
- matched formatting / naming to zingolibs CI

**Comment by zancas** [comment]
I think the best reviewer for this is @juanky201271 .   He definitely understands this codebase better than anyone else!

**Review by juanky201271 — DISMISSED** [review]
Seems perfect.

**Review by juanky201271 — APPROVED** [review]
Perfect.

**Pull request merged**
