### PR TITLE
Privacy switch & settings new parameter

### PR DESCRIPTION
**Pull request by juanky201271**
A new settings parameter added, `privacy` (High / Normal) -> `Normal` by default.

I changed the amounts (ZEC & USD) components:
- privacy High -> it shows a pattern like this: `z -.---- ZEC` or `-.-- USD` and if you tap on it, it shows the real amount for 5 seconds.
- privacy Normal -> nothing changed, the same behavior than before.

I changed the QR Addresses, in privacy HIGH are hidden and if you tap on them, it reveal for 5 seconds, as well.

I changed the Seed screen as well.

I changed the Header adding a new toggle for this, because the User wants to change the `privacy` fast, without to go to the setting screen and do the change.

### CODE REVIEW

**Comment by juanky201271** [comment]
ready for review...

**Review by Oscar-Pepper — CHANGES_REQUESTED** [review]
can we have HIGH in lower case in privacy settings?

**Comment by juanky201271** [comment]
> can we have HIGH in lower case in privacy settings?

done!

**Review by Oscar-Pepper — APPROVED** [review]
brilliant work!

**Pull request merged**
