### PR TITLE
New custom fee setting for advanced mode

### LINKED ISSUE #488: Advanced Mode - Add a new setting to customize the fee
Seems interesting to add this new setting for Advanced Users. Even if we implement ZIP 317 in zingolib, can be useful for users to have the possibility of set the Fee to whatever value they want.
Valid Range: from max ZEC in the wallet to 0.00000001 [the user need to know about this].
@zancas idea.

### PR DESCRIPTION
**Pull request by juanky201271**
Ref: #488 
If the user set a custom fee, this value apply in every transaction, only in advanced mode.

The `send` command of `zingolib` only accepts three parameters (address, amount & memo), and the fee for all txs is fetched from here: `zcash_primitives::transaction::fees::zip317::MINIMUM_FEE`, as a fixed value.

### CODE REVIEW

**Comment by fluidvanadium** [comment]
this seems strange to me.. but i like adding extra options for advanced users, as long as it still makes sense from a ux perspective

**Comment by juanky201271** [comment]
> this seems strange to me.. but i like adding extra options for advanced users, as long as it still makes sense from a ux perspective

before we implement the ZIP 317.... this new feature can have some sense... but after the ZIP 317.... mmmmm, nobody is going to set a custom fee, but if some uber-advanced user want to put a custom fee... well, they can do that.

**Comment by fluidvanadium** [comment]
we just need to implement the ZIP 317 then

**Comment by juanky201271** [comment]
closing... Ref: https://github.com/zingolabs/zingolib/issues/466

**Pull request closed without merging**
