### PR TITLE
A couple of UI issues fixed in send screen

### PR DESCRIPTION
**Pull request by juanky201271**
Two enhancements:
- Adding another text `spendable` for dollars, same as ZEC. The users usually get confused about this dollar amount.
- Make everything clickable when the Keyboard is open. (send, seed, ufvk & settings) 

Working on a new send flow for basic users, because that screen is really hard to understand.

### CODE REVIEW

**Review by zancas — COMMENTED** [review]
I looked over these changes.  They seem fine, but probably @fluidvanadium or @Oscar-Pepper or Edickson, should check out how they show up in the app?

**Comment by juanky201271** [comment]
> I looked over these changes. They seem fine, but probably @fluidvanadium or @Oscar-Pepper or Edickson, should check out how they show up in the app?

Screenshot_1694617477

**Comment by juanky201271** [comment]
New flow for Basic Send:
- click on the bottom tab `Send` (Maybe the basic user is looking for `Pay` instead `Send`)
- Alert with two options: 1. `Send/Pay` & 2. `Pay with Tip`

Option 2:
- Scanner Screen. (Step 1) for scanning the address.
- Screen with 3 fields `Amount ZEC` & `Amount $` (Step 2) for setting the amount to send/pay. The user can put a memo as well.
- Scanner Screen. (Step 3) for scanning the tip address.
- Screen with 3 fields `Amount ZEC` & `Amount $` (Step 4) for setting the amount to pay the tip. The user can put a tip memo as well.
- Confirmation screen (Step 5)

Option 1:
- Scanner Screen. (Step 1) for scanning the address.
- Screen with 3 fields `Amount ZEC` & `Amount $` (Step 2) for setting the amount to send/pay. The user can put a memo as well.
- Confirmation screen (Step 3)

**Comment by juanky201271** [comment]
Maybe in another moment... closing...

**Pull request closed without merging**
