### PR TITLE
New wallet from ufvk

### PR DESCRIPTION
**Pull request by AloeareV**
This adds a `new_wallet_from_ufvk` rust function, and also adds it to the android ffi. I'm not familiar with the iOS ffi structure, so this needs a corresponding new Objective-C/Swift(?) function corresponding to new_wallet_from_fvk to be iOS compatible.

### CODE REVIEW

**Comment by juanky201271** [comment]
> This adds a `new_wallet_from_ufvk` rust function, and also adds it to the android ffi. I'm not familiar with the iOS ffi structure, so this needs a corresponding new Objective-C/Swift(?) function corresponding to new_wallet_from_fvk to be iOS compatible.

Do you mean: `init_from_ufvk`?. I will add ASAP a commit here with the same function in IOS...

**Comment by juanky201271** [comment]
@AloeareV 

I got this error building...

#13 534.2    Compiling rustlib v1.0.1 (/opt/zingo/rust/lib)
#13 534.5 error[E0382]: borrow of moved value: `lightclient`
#13 534.5   --> lib/src/lib.rs:27:22
#13 534.5    |
#13 534.5 21 | fn lock_client_return_seed(lightclient: LightClient) -> String {
#13 534.5    |                            ----------- move occurs because `lightclient` has type `LightClient`, which does not implement the `Copy` trait
#13 534.5 22 |     let lc = Arc::new(lightclient);
#13 534.5    |                       ----------- value moved here
#13 534.5 ...
#13 534.5 27 |     let seed = match lightclient.do_seed_phrase_sync() {
#13 534.5    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ value borrowed here after move
#13 534.5
#13 534.5 For more information about this error, try `rustc --explain E0382`.
#13 534.5 error: could not compile `rustlib` due to previous error
#13 534.5 warning: build failed, waiting for other jobs to finish...

**Comment by juanky201271** [comment]
@AloeareV I'm sorry, I rebased this branch with dev. I did that because the tests were failing.., I hope now those tests are going to work...

But the test fails because there is an error in rust layer.

**Comment by AloeareV** [comment]
Whoops.....new commit should fix it!

**Comment by juanky201271** [comment]
> Whoops.....new commit should fix it!

and actually works, thanks.

**Comment by juanky201271** [comment]
I fixed the `rustFFi` object including `initfromufvk`, and this way I guess the integration tests is going to work.

**Review by juanky201271 — APPROVED** [review]
I think is going to work, maybe we'll have to adjust something, but It's good enough.

**Pull request merged**
