### PR TITLE
Report Sync Screen better ux when the App come back from background

### PR DESCRIPTION
**Pull request by juanky201271**
When you go to the background (Android) the App start a new Sync process in background, that's good. But when the App go to the foreground again, the App have to do a lot...

- first: finished the BS, take a few seconds.
- second: start again a new sync process, take a few seconds as well.

If you are in any screen, you don't aware of this `seconds` (you can see the `stop` icon during several seconds...), but if you are in the Report Sync Screen, it's different. You have to wait to those task & seconds... I put another & better message besides `loading` and I hide all the info that can be confusing or partially printed.

### CODE REVIEW

**Comment by juanky201271** [comment]
Let's check out the last commit with fixes from linter & typescript checkers... to make sure that these tools not include errors in our code.

**Comment by zancas** [comment]
Adding @Oscar-Pepper to this, since he'll be focused BS soon.

Removing myself.

**Comment by fluidvanadium** [comment]
i like the automated edits.

**Review by fluidvanadium — APPROVED** [review]
looks good! i like what the autocleaners are doing to the code

**Pull request merged**
