### PR TITLE
change logobig to phase1 logo change, version 1s

### LINKED ISSUE #79: We'd like a new "phase 1" logo
Phase 1 is meant to be quick but distinct from our origins.

Also, for now, the ios logo is out of scope as we are only building for android.

Phase 2 is planned to be more considered and refined.

### PR DESCRIPTION
**Pull request by dannasessha**
First of probably two versions on offer today.

Might Fix #79 .

### CODE REVIEW

**Comment by dannasessha** [comment]
Version 1.1 adds a little blur on the coins.

**Comment by dannasessha** [comment]
Version 1.2 adds a fairly simple "leather" pattern to the wallet exterior.

**Comment by dannasessha** [comment]
version 1.3 switches the coins, but introduces some slopiness :(

**Comment by dannasessha** [comment]
My current pick of this series is probably 1.1, with 1.2 in second.

**Comment by AloeareV** [comment]
I think I also like v.1.1 the best. Didn't notice the coin blur until you pointed it out, but I do think it's an improvement. The leather pattern on 1.2 and 1.3 is interesting, but it's darker and so it doesn't contrast with the inside of the wallet. A lighter leather texture could be worth trying.

**Comment by zancas** [comment]
Let's merge the current favorite and keep iterating!

**Comment by dannasessha** [comment]
I think I really like 2.4 in #81 ! but it is "wild and crazy" so I am okay with one of these if everyone else wants one of them or just really doesn't like the wild ones.

**Review by zancas — APPROVED** [review]

**Comment by dannasessha** [comment]
Closing for now.

**Pull request closed without merging**
