### PR TITLE
history line when confirming fixed

### PR DESCRIPTION
**Pull request by juanky201271**
on top of: #675

We split the `pending` status in two:
- `transmitted`
- `in mempool`

Following the advice of @Edicksonjga these are the final screens:

image(1)

image(2)

image(6)

### CODE REVIEW

**Comment by juanky201271** [comment]
@edicksonjga can you, please, test this PR in your local AS... trying to reproduce the ghost transaction `bug` which the new transaction is in the App but it isn't in the blockchain (mempool)...???? thanks.

**Comment by Edicksonjga** [comment]
I understand that we care and want to keep the user informed about some rare cases that may occur, but if we ignore everything that the user doesn't know we are going to fill the UI again with texts/icons/elements when previously we had changed in the History how the transaction list is displayed making it simpler.

Regarding the changes made, I think the **Transmitted** text in the Transaction Details should be different from the **In Mempool** text.

**Review by Edicksonjga — COMMENTED** [review]
Let's make the Transmitted text in the transaction details different from In Mempool.

**Comment by juanky201271** [comment]
> Let's make the Transmitted text in the transaction details different from In Mempool.

This PR is already `merged`, please open an issue with the new text for `transmitted` that you propose and I'll change right away... Thanks @Edicksonjga

**Pull request merged**
