### PR TITLE
change logobig to phase1 logo, version 2s

### PR DESCRIPTION
**Pull request by dannasessha**
Version 2 images. This will probably be the last of the offerings from me, today.

Might solve #79 , but also might #80 .

Can you guess which ones I am more excited about??

### CODE REVIEW

**Comment by dannasessha** [comment]
version 2.2 adds circular element behind black coin and increases saturation of orange coin.

**Comment by dannasessha** [comment]
Version 2.3 adds **INDUSTRIAL STRENGTH!!**

**Comment by dannasessha** [comment]
Version 2.4  adds dimensionality to the orange coin.

**Comment by dannasessha** [comment]
I think I like 2.4 best out of this series right now, followed by 2.3, 2.2, 2.1 in that order.

**Comment by AloeareV** [comment]
I like the gear, but prefer the less saturated orange coin. Not sure if the lower saturation would work with the shine on the coin in version 4, which is also neat.

**Review by AloeareV — APPROVED** [review]
Still torn between 2.4 and 1.1, but I'm gonna merge this one in and we can revisit this later if we want to!

**Pull request merged**
