### PR TITLE
New type for translate function

### PR DESCRIPTION
**Pull request by juanky201271**
I cherry picked from this: #216 and I closed it.

### CODE REVIEW

**Review by AloeareV — DISMISSED** [review]
Great!

**Review by AloeareV — DISMISSED** [review]
Great!

**Comment by AloeareV** [comment]
Darn it! I keep forgetting that using the web ui messes up commit signing sometimes.

**Comment by AloeareV** [comment]
Alright, the rebase has forced the checks to rerun, I can't merge until they're finished. @juanky201271 I've approved this PR, I plan to merge it as soon as CI passes, if you notice them being finished before I do, feel free to merge it!

**Comment by AloeareV** [comment]
Build is failing on CI, for some reason, it passes locally. Might be related to the latest dev changes, if we're not using a pinned version.. It may take some work on my end to fix this.

**Comment by juanky201271** [comment]
OMG, I did it as well... I rebased without signed, arghhhhhhhhhhhhhhhhhhhhh

**Comment by juanky201271** [comment]
OMG, this is nightmare...

**Pull request closed without merging**
