### PR TITLE
Put activity spinner while fetching price

### LINKED ISSUE #269: PriceFetcher component behaviour when the user ask for price the first time
I noticed that the first time that I click on this component can be delayed for a few seconds. Seems like the button/component doesn't work. 

Can be a good idea if when the user click on the button, automatically change to some icon with dots or something, until the async price come back with the value...

### PR DESCRIPTION
**Pull request by juanky201271**
Ref: #269

### CODE REVIEW

**Comment by juanky201271** [comment]
@zancas maybe you can choose a reviewer.

**Comment by juanky201271** [comment]
@zancas @fluidvanadium this is ready for review too, thanks in advance.

**Comment by zancas** [comment]
OK..  so this is in @fluidvanadium 's court?

**Review by fluidvanadium — APPROVED** [review]
works and looks good

**Pull request merged**
