### PR TITLE
UI/UX enhancements

### LINKED ISSUE #408: Application crashes when importing using VK
**Zingo v.1.2.4** (latest release) crashes when I try to import the wallet in display-only mode using the display key.

**Steps:**
1. Open the wallet
2. Restore wallet with display key
3. Enter the data
4. Restore
5. The wallet crashes a few seconds after launching

https://github.com/zingolabs/zingo-mobile/assets/37910384/2abe4b67-b5e1-4802-9611-3268cdd98359

**Expected behavior:**

The wallet starts, connects to the server and begins the synchronization process.

**Current behavior:**

The wallet crashes a few seconds after launching.

**Device:**
Techno Phantom X
Android 11
Zingo Wallet 1.2.4 (125)

**Edited:**

The app works fine when restored using the seed phrase, it only crashes when the VK is used, the same on three devices:

Techno Phantom X (arm64)
Xiaomi Redmi 7A and 9A (armv7l and armv8l 32bits operating system).

### LINKED ISSUE #606: change the IOS instructions in readme
we need to put somewhere that for build & run the user needs to be inside of `Zingo-mobile` folder. something like: `cd Zingo-mobile`

### PR DESCRIPTION
**Pull request by juanky201271**
- Confirm Transaction Screen (shielding & sending): The text about `finishing syncing to be able to send` was removed. I think the users were so confusing about this, because it is not related with shield or send.
- If the memo have an UA to reply to, when the user tap on it, the App only copy/paste the UA, ready to paste like an address. (I did here the simplest solution because this is temporary waiting to have the authenticated memo mechanism to reply to). 
- Primary color (green) changed for `basic` mode to `Tron Blue`...

I tested all manually.

- Also I clarify some parts of the Readme, Ref: #606
- Using `cargo-ndk` to build the rust libs for Android (Docker & CI).
- Finally we fixed the UFVK Bug... Ref: #408

### CODE REVIEW

**Comment by zancas** [comment]
I think these are great improvements.   I want to roll another release next week.   I vote we put them in that release.

**Review by fluidvanadium — APPROVED** [review]
this runs in my emulator 

i think the basic background should be lighter for lower contrast. what about #3652c4

**Comment by zancas** [comment]
Can we defer more style tweaks until we get more user feedback?    If we leave the background the same between modes then the only difference is the wire-frame colors.

**Review by zancas — APPROVED** [review]

**Comment by juanky201271** [comment]
> this runs in my emulator
> 
> i think the basic background should be lighter for lower contrast. what about #3652c4

Thanks, I take note of this color to try depending of the users feedback...

**Pull request merged**
