### PR TITLE
New setting prop for mode: basic / expert

### LINKED ISSUE #394: Basic Mode
@zancas @AloeareV @Oscar-Pepper @fluidvanadium @Edicksonjga 

## Let's talk about `Basic Mode`...
* Basic Mode will be the Mode `by default`
## Installation: 
When the user install the App, directly it is going to go to `receive` with only the UA. When the wallet is new, with no balance & no transactions... the only thing the user can do is: give someone the UA to receive funds...
## Drawer Menu: 
* About
* Settings (only mode, privacy, currency & language)
* Wallet Seed (only if the wallet have funds or transactions)
* Financial Insight (only if the wallet have transactions)
## Tabs:
* History - I think the user needs to see the transaction list (only if the wallet have txs)
* Send - I think the user needs to use this screen. (only if the user have some funds)
* Receive - Here we put only the UA, no Z and no T.
## Settings:
* Mode: Basic / Advance.
* Privacy: High / Normal
* Language: English / Spanish.
* Currency: No currency / US Dollars.

These are the main ideas in my head. Please let me know your opinions about everything...

### PR DESCRIPTION
**Pull request by juanky201271**
* New setting called `mode` with `basic` and `expert` values. 
* This new setting is working in the settings screen.
* With fresh install or with device storage removed - basic mode - The App create a new wallet (new seed) & go directly to receive screen.
* No option for send screen until the total balance > 0.
* No option for history screen until there are some transactions.
* Settings screen have a few options: mode of course, privacy, currency & language.
* The drawer menu have two options in basic mode (about zingo & settings). Some of other options appear with balance and/or transactions.
* shield button in basic mode.
* new snapshot tests.
* e2e/change_custom_testnet_server.test.js updated.
* e2e/loadtestwallet.js updated.
* The Icon in the Header for the Fund pools screen is not necessary for basic mode.
* The Icons in the Header for Sync report screen are not necessary as well.
* bottom tabs - when selected only shows up the icon"
* `wallet seed` option changed for basic mode.
* `wallet seed` button changed for basic mode.
* button border changed.
* The Icons in the Header for internet status are not necessary for basic mode.

TODO:

### CODE REVIEW

**Comment by fluidvanadium** [comment]
edit: order


Screenshot from 2023-06-30 04-47-05
Screenshot from 2023-06-30 04-47-17
Screenshot from 2023-06-30 04-47-28
Screenshot from 2023-06-30 04-47-54

**Comment by fluidvanadium** [comment]
works!

button color is not quite right

advance user -> advanced user (or PR 4: https://github.com/juanky201271/zingo-mobile/pull/4/files)

**Comment by fluidvanadium** [comment]
can we update this test: e2e/change_custom_testnet_server.test.js to follow the new flow?

**Comment by juanky201271** [comment]
> works!
> 
> button color is not quite right
> 
> advance user -> advanced user (or PR 4: https://github.com/juanky201271/zingo-mobile/pull/4/files)

PR merged!

Yes, the button color is weird... that was a test and it doesn't work...

**Comment by juanky201271** [comment]
@fluidvanadium I revert the button color.

**Comment by fluidvanadium** [comment]
im still finding grey buttons
Screenshot from 2023-06-30 23-32-51

**Comment by juanky201271** [comment]
> im still finding grey buttons Screenshot from 2023-06-30 23-32-51

Yes, I'm trying in the bottom menu tabs to use the `primaryDisabled` color because if have `primary` color the user can think about it like something clickable... and it's not. When the tab is selected (green) it become in something not clickable... and maybe with the `disabled` color is much more intuitive... I don't know, it's just an idea, what do you think?
Also, in the selected tab we can hide the text, like `send`, and leave only the `icon`... sounds good, right?
@fluidvanadium

**Comment by juanky201271** [comment]
button send inactive:
Screenshot_1688395513

button send active:
Screenshot_1688395562

* new border for enabled & disabled buttons.
* bottom tabs only with icon when selected.
* there is not two buttons with `Send`.

I hope this can be a solution for `basic mode`, any idea is welcome.

**Comment by fluidvanadium** [comment]
Screenshot from 2023-07-03 20-40-28

here is a small glitch

**Review by fluidvanadium — APPROVED** [review]
basic mode is excellent so far

**Pull request merged**
