### PR TITLE
added a patch to react-native-camera for fixing errors running zingo …

### PR DESCRIPTION
**Pull request by Oscar-Pepper**
…in android studio

### CODE REVIEW

**Review by juanky201271 — CHANGES_REQUESTED** [review]
Can you please, take a look to the readme.md and make changes according to this new way to build the App... Thanks in advance.

**Comment by Oscar-Pepper** [comment]
> Can you please, take a look to the readme.md and make changes according to this new way to build the App... Thanks in advance.

ok i will test a fresh clone of this now but i believe the changes should be automatic so the README should not change

**Comment by Oscar-Pepper** [comment]
ok i have confirmed the README does not need to change

**Comment by juanky201271** [comment]
> ok i have confirmed the README does not need to change

So, if I clone the repo, for Android and I do `yarn install` is enough??? I can do `yarn react-native start` and run the App with Android Studio... That's it?

**Comment by Oscar-Pepper** [comment]
> > ok i have confirmed the README does not need to change
> 
> So, if I clone the repo, for Android and I do `yarn install` is enough??? I can do `yarn react-native start` and run the App with Android Studio... That's it?

Correct, ```patch-package``` and ```postinstall``` added to package.json so they are pulled in automatically and when you run ```yarn install``` it reads the files in the new ```patches``` directory and alters the node modules (i.e. RNCamera) automatically. I have tested this on a fresh git clone of zingo-mobile

**Review by juanky201271 — APPROVED** [review]
Looks really good...

**Pull request merged**
