### PR TITLE
New multi txs summary list - History screen

### PR DESCRIPTION
**Pull request by juanky201271**
- RN upgraded to 0.70.14.
- New summary list for multi send & receive transactions. Only for Advance mode.
- Snapshots updated.

### CODE REVIEW

**Comment by juanky201271** [comment]
BASIC MODE:

You can see here the 4 types of txs:
- First row: Multi Sent (with 2 UA's & 2 amounts & fee) You can see the two UA's & amounts in the detail screen.
- Second row: Sent (with 1 UA & 1 amount & fee)
- Third row: Send-to-self (with only fee)
- Fourth row: Received (with only amount)

For **basic mode**:
image

**Comment by juanky201271** [comment]
ADVANCED MODE:

You can see here the 5 types of txs:
- First row: Multi Sent (with 2 UA's & 2 amounts & fee & TOTAL)
- Second row: Sent (with 1 UA & 1 amount & fee)
- Third row: Send-to-self (with only fee)
- Fourth row: Received (with only amount)
- Second screen, first row: Multi Received (with 3 pools & 3 amount & TOTAL)

For **advanced mode**:
image

image

**Comment by fluidvanadium** [comment]
this is good, but maybe basic mode should be more basic. grizelda likely does not need the transaction hash

**Comment by juanky201271** [comment]
> this is good, but maybe basic mode should be more basic. grizelda likely does not need the transaction hash

Actually you are right, I'm going to change this with only the UA....

**Comment by Edicksonjga** [comment]
> this is good, but maybe basic mode should be more basic. grizelda likely does not need the transaction hash

I disagree and stop making change thinking about someone who does not exist.

The TXID may not be a basic element in a transaction, but it is important because through it you can track the transaction made.

I am also not comfortable with the advanced design showing every detail from the history, for that they have the DETAILS window/screen when opening the transaction. What used to be simple now looks cluttered. @juanky201271 @fluidvanadium

**Comment by juanky201271** [comment]
We need more opinions: @AloeareV @Oscar-Pepper @zancas

**Comment by juanky201271** [comment]
BASIC MODE slightly different:

- Sent -> if only have 1 UA, the App shows the UA instead the txID.
- Multi Sent -> The App shows the txID because the tx have more than one UA's.

The Fee is not necessary for basic users.

image

**Comment by juanky201271** [comment]
ADVANCED MODE new:

- Sent -> You can see the UA's in all of sent txs.
- Received -> You can see the pool if there are more than one o there is only one but is not Orchard. And the pools are in one line.

image

image

**Comment by juanky201271** [comment]
What do you think? @Edicksonjga @zancas @fluidvanadium @Edicksonjga @AloeareV

**Comment by AloeareV** [comment]
Taken a couple looks at this...haven't spent the time to thoroughly sign off in it yet, looks good so far

**Comment by juanky201271** [comment]
> Taken a couple looks at this...haven't spent the time to thoroughly sign off in it yet, looks good so far

something do you want to share about your tests? @AloeareV

**Comment by Oscar-Pepper** [comment]
My opinion is that the history screen should look as clean and minimal as possible. I think the best way to do this is to have only a txid and the value transfer amount (total outgoing for spend or total incoming for receive). I think that all information about multi-sends, fees and pools should be in the details screen only....
i think that when we have authentic address book we can replace txid with the nym if its a single send and that will look really clean.

@juanky201271 i dont understand replacing the txid with UA for sends if only one UA... do you mean if we are only sending to one UA? if that is so, and we are showing the recipients UA, then i like this as it is the starting point for authentic address book nyms

**Comment by juanky201271** [comment]
> My opinion is that the history screen should look as clean and minimal as possible. I think the best way to do this is to have only a txid and the value transfer amount (total outgoing for spend or total incoming for receive). I think that all information about multi-sends, fees and pools should be in the details screen only.... i think that when we have authentic address book we can replace txid with the nym if its a single send and that will look really clean.
> 

My motivation for this UI change was: If someone uses multi-send or multi-receive that I think there are a very few people, even nobody for now... they would like to see this info faster in the history list, otherwise if this user are looking for a specific transaction (multi) the only way to found it, is clicking in details of hundreds of txs history item... this can take a while. And on the other hand... the normal user won't se any difference in the UI, only the fee, which is useful for the advanced user. Last thing... the basic user won't be affected at all...

> @juanky201271 i dont understand replacing the txid with UA for sends if only one UA... do you mean if we are only sending to one UA? if that is so, and we are showing the recipients UA, then i like this as it is the starting point for authentic address book nyms

As you said this is the first step towards the address book... if a `sent` tx have only one UA (can be a contact in the address book) what is more useful to see... the txid that most of the times the user don't care about it, or the UA who received the money?????
If the user want to see more details of this tx... can click on details & click on txid & click on the link to zcashexplorer...
IMO.

**Comment by Oscar-Pepper** [comment]
ok i am onboard with multi-sends in history if it does not change UI for single-sends. I am not yet convinced that we should clutter the history screen with which pools we received to, and also showing both TXID and UA. will these show up in single sends/receives too?

i think a non-cluttered solution is to only show UAs with no TXID for sends (txid can go in the details). when we implement address book then the history screen will just be a list of nyms, time, date, and amount. where some of these are grouped together in the case of multi-sends.

**Pull request closed without merging**
