### PR TITLE
Android Studio configuration improvements

### PR DESCRIPTION
**Pull request by juanky201271**
The purpose of this PR is to set the simplest configuration using AS (Koala 2024 version) without any tweaking. 
- some lib versions recommended by AS bumped.
- kotlin version: 1.8.20
- java 17
- Gradle 8.2
- AGP 8.2.1
- cargo update -> zingolib.

This is the configuration that we used to set up the AS of @edicksonjga

### CODE REVIEW

**Comment by zancas** [comment]
@sebastianlujan can you please make this PR one of your top priorities?

**Comment by sebastianlujan** [comment]
Yes sure, I will work on it.

**Comment by juanky201271** [comment]
@sebastianlujan Any update?

**Comment by sebastianlujan** [comment]
Fully works.

**Pull request merged**
