### PR TITLE
Restore Wallet from viewing key

### LINKED ISSUE #380: Suggestion for High Privacy and Normal
The text on the button to switch between High Privacy and Normal Privacy causes a visual error (bug🐛) on some devices.

Steps:

1. Open in to Zingo Wallet
2. Go to the button that allows you to hide sensitive information
3. You can see that the word **Privacy** is very close to the logo (especially in spanish: **Privacidad**).

On devices with small screens it can be seen over the Zingo logo.

**Suggestion:**

Delete the word **Privacy** and leave the button: [Normal 🔓] / [High 🔒], or leave only the icons [🔒] / [🔓] and add **tooltips** that are displayed when touching them.

Zingo Wallet v.1.2.2

**Devices:**
Redmi 9A
Techno Phantom X
Android 11

### LINKED ISSUE #381: BUG: The port is changed automatically
When trying to set a custom server with a port  other than `9067` the port is changed.

Steps:

1. Open Zingo Wallet and enter **Settings** from the Menu
2. Go to Server and set up a custom server
3. Add a different port than `9067`
4. Save
5. The port automatically changes to `9067`

**Expected behavior**
The port should not change and the exact settings you are customizing should be saved

**Current behavior**
The port changes when in the customization it is different from 9067, even with any binding.

https://github.com/zingolabs/zingo-mobile/assets/37910384/9a574190-b578-4289-afad-5ad518e7a8cf

https://github.com/zingolabs/zingo-mobile/assets/37910384/fe422ec1-b476-4e8b-b420-d8bd4436b280

_Zingo Wallet 1.2.2_

**Device:**
Techno Phantom X
Android 11

### PR DESCRIPTION
**Pull request by juanky201271**
I added the possibility of `restore from UFVK` which open a watch-only wallet.
The App keep working the same way, the `send` option disappear, and the `wallet seed` become `wallet viewing key`.

Easy to explain, but a lot of changes.

Ready for testing & reviewing...

### CODE REVIEW

**Comment by fluidvanadium** [comment]
hmm, here's what i got so far. i got that viewkey from zingo-cli

Screenshot from 2023-06-04 15-26-41
Screenshot from 2023-06-04 15-28-36

**Comment by juanky201271** [comment]
Thanks @fluidvanadium , A lot of thing to adjust... I need to test it in the emulator...

**Comment by fluidvanadium** [comment]
Screenshot from 2023-06-05 18-49-23

**Comment by juanky201271** [comment]
> Screenshot from 2023-06-05 18-49-23

Question: What is your `server` here? and the UFVK is from mainnet?

**Comment by fluidvanadium** [comment]
> Question: What is your `server` here? and the UFVK is from mainnet?

mainnet.lightwalletd.com, yeah. i will test the seed in cli

**Comment by fluidvanadium** [comment]
Screenshot from 2023-06-05 19-03-52
it works in cli

**Comment by juanky201271** [comment]
> Screenshot from 2023-06-05 19-03-52 it works in cli

Ok, I think now is going to work... (I need to work on the ascetics... of course, I will do soon)

**Comment by juanky201271** [comment]
I need to do some testing in IOS as well... don't merge yet...

**Comment by juanky201271** [comment]
Ready for review, as well.

**Comment by fluidvanadium** [comment]
maybe there should only be a RESTORE WALLET button and it should restore either a seed or a viewkey?

**Comment by fluidvanadium** [comment]
Screenshot from 2023-06-07 19-05-11

this is my favorite screen. its so detailed and useful in regular seed mode. however right now in viewkey mode i cant see the birthday and sync status properly

**Comment by juanky201271** [comment]
> Screenshot from 2023-06-07 19-05-11
> 
> this is my favorite screen. its so detailed and useful in regular seed mode. however right now in viewkey mode i cant see the birthday and sync status properly

Me too, this report is the best... but I'm waiting for this PR: https://github.com/zingolabs/zingolib/pull/367
Because I need to get the birthday from `zingolib`....

**Comment by juanky201271** [comment]
> maybe there should only be a RESTORE WALLET button and it should restore either a seed or a viewkey?

Yes, I thought a lot on that, and after.... I convince myself is less confusing for the `normal` user, maybe we can put two buttons for `Basic Mode`, and only one for `Advance Mode`... what about that?

**Comment by fluidvanadium** [comment]
> > maybe there should only be a RESTORE WALLET button and it should restore either a seed or a viewkey?
> 
> Yes, I thought a lot on that, and after.... I convince myself is less confusing for the `normal` user, maybe we can put two buttons for `Basic Mode`, and only one for `Advance Mode`... what about that?

after pressing the RESTORE WALLET button, there could be an advanced option for viewkey

**Comment by juanky201271** [comment]
> > > maybe there should only be a RESTORE WALLET button and it should restore either a seed or a viewkey?
> > 
> > 
> > Yes, I thought a lot on that, and after.... I convince myself is less confusing for the `normal` user, maybe we can put two buttons for `Basic Mode`, and only one for `Advance Mode`... what about that?
> 
> after pressing the RESTORE WALLET button, there could be an advanced option for viewkey

Really good point, the basic user maybe don't understand what is a Ufvk, then maybe for `basic Mode` -> restore only from `seed`... I think this is a good idea...

I'm resolving the conflicts, though.

**Comment by juanky201271** [comment]
@fluidvanadium If want to test this more, you need to build the `rust` library. The sync report will work.

**Comment by juanky201271** [comment]
> > > > maybe there should only be a RESTORE WALLET button and it should restore either a seed or a viewkey?
> > > 
> > > 
> > > Yes, I thought a lot on that, and after.... I convince myself is less confusing for the `normal` user, maybe we can put two buttons for `Basic Mode`, and only one for `Advance Mode`... what about that?
> > 
> > 
> > after pressing the RESTORE WALLET button, there could be an advanced option for viewkey
> 
> Really good point, the basic user maybe don't understand what is a Ufvk, then maybe for `basic Mode` -> restore only from `seed`... I think this is a good idea...
> 
> I'm resolving the conflicts, though.

I don't want to mix things up here... because I'm going to start working on `Basic` / `Advance` mode really soon... I prefer to merge this with two buttons for now. We can discuss the two different modes when all of this code are landed...

**Review by fluidvanadium — APPROVED** [review]

**Pull request merged**
