### PR TITLE
fix readme, add_builder_user step removed for add_android_ndk, set -e

### PR DESCRIPTION
**Pull request by skyl**
Followup from #77

### CODE REVIEW

**Comment by skyl** [comment]
worksforme - can confirm and merge? @AloeareV @zancas ? Feel free to squash merge to a single commit.

**Comment by skyl** [comment]
should close #78 as well

**Comment by zancas** [comment]
I am +1 if it works for you.  If it breaks for @juanky201271 we can circle back.   We need to give them a heads up though so I am cross-posting an issue.

**Review by zancas — APPROVED** [review]
LGTM We might experience a build regression in other dev environments, which we'll need to address when they arise.

**Pull request merged**
