### PR TITLE
Shield command for all funds

### PR DESCRIPTION
**Pull request by juanky201271**
How works for now:

- The button shows up when you have any funds in sapling or transparent.
- When you click on this button, the App shield `all` your funds in the `orchard pool`.

I think this is not the idea exactly, @zancas no rush, when you have the time can you explain how this feature should work? Thanks.

### CODE REVIEW

**Comment by juanky201271** [comment]
I rebased this branch with the other branch with the new version...

**Comment by juanky201271** [comment]
@AloeareV tell me when you land the fix for this... and I can keep going with this, thanks in advance.

**Comment by AloeareV** [comment]
> @AloeareV tell me when you land the fix for this... and I can keep going with this, thanks in advance.

Sorry, forgot to tell you! Fix landed this morning

**Comment by juanky201271** [comment]
I tested all the combinations:

- o + z -> OK.
- o + z + t -> OK.
- o + t -> OK.
- z + t -> OK.
- z -> OK.
- t -> OK.

Every time the amount landed in the `orchard pool`.
Ready for review.

**Comment by juanky201271** [comment]
I'm going to add a checkbox with two values when the user have the possibility of shield from transparent & sapling... so the user can decide if to shield one pool, another pool, or both at the same time. @zancas This sounds good to you?

**Comment by juanky201271** [comment]
> I'm going to add a checkbox with two values when the user have the possibility of shield from transparent & sapling... so the user can decide if to shield one pool, another pool, or both at the same time. @zancas This sounds good to you?

No answer... means ok? I think so. I added a couple of links with the `shield button`, the user can select `transparent` or `sapling` or `all`...

**Comment by juanky201271** [comment]
Ready to review!.

**Review by Oscar-Pepper — APPROVED** [review]
looks great

**Pull request merged**
