### PR TITLE
Keep Awake the App/Screen while it's syncing

### PR DESCRIPTION
**Pull request by juanky201271**
We have a user feedback about this feature. While the App is active & syncing the screen keeps Awake.
@zancas

### CODE REVIEW

**Comment by zancas** [comment]
How can we test this?   Do we have a test of this?

**Comment by juanky201271** [comment]
> How can we test this? Do we have a test of this?

1. I'm not be able to test this in the emulator, I tested it in my Android Physical device.
2. No. If I couldn't test it in the emulator... it seems likely I won't test it in e2e.

Maybe @fluidvanadium can achieve/do it. I hope so, and good luck.

**Comment by juanky201271** [comment]
I was trying to add a test for this, but I don't see the way to ask in e2e detox about if the screen is awake or not while syncing...

**Comment by juanky201271** [comment]
> I was trying to add a test for this, but I don't see the way to ask in e2e detox about if the screen is awake or not while syncing...

I got it, I did a test for this. Ready for review & merge.

The result of the test:

C:\Users\juank\github\zingo-mobile-juanky\android>yarn detox test screen -c android.emu.debug
yarn run v1.22.15
$ C:\Users\juank\github\zingo-mobile-juanky\node_modules\.bin\detox test screen -c android.emu.debug
17:16:26.295 detox[355324] B jest --config e2e/jest.config.js screen
17:17:01.291 detox[345708] i screen_awake.test.js is assigned to emulator-18026 (Pixel_6_API_30_1)
17:17:13.690 detox[345708] i Kepp the screen awake while syncing.: loads a wallet
17:17:19.370 detox[345708] i Kepp the screen awake while syncing.: loads a wallet [OK]
17:17:19.372 detox[345708] i Kepp the screen awake while syncing.: When App is syncing -> The screen have to be awake all the time
17:17:39.476 detox[345708] i screen off timeout: 10000
17:17:39.553 detox[345708] i Kepp the screen awake while syncing.: When App is syncing -> The screen have to be awake all the time [OK]

 PASS  e2e/screen_awake.test.js (72.063 s)
  Kepp the screen awake while syncing.
    √ loads a wallet (5679 ms)
    √ When App is syncing -> The screen have to be awake all the time (20181 ms)

Done in 73.99s.

**Review by fluidvanadium — APPROVED** [review]
great!

i have concerns about intermittent internet scenario. may be difficult but should be possible to create a test for that circumstance

**Pull request merged**
