### PR TITLE
New version zingo 1.3.0 128

### PR DESCRIPTION
**Pull request by juanky201271**
New production version of Zingo.

I used to build the App:
* zingolib -> commit: https://github.com/zingolabs/zingolib/commit/f8c914a5894fd448d1b77556ad239c1f4f0ddad2
* zingo-mobile -> commit: https://github.com/zingolabs/zingo-mobile/pull/478/commits/3c5758f513056f56e63d0a48ac88c67d869398a2

What's new:
* Faster Syncing with the ShardTree witness update.
* Significant increase in test coverage
* New transaction explorer.
* New server on the list.
* Privacy Level Info Added.
* Bugs fixed and minor improvements.

@fluidvanadium @zancas @AloeareV @Oscar-Pepper @idky137 

Everything was tested by @edicksonjga.

### CODE REVIEW

**Review by Oscar-Pepper — CHANGES_REQUESTED** [review]
what do you think about adding to 'whats new' some points:
- increased test coverage
- upgraded test framework including:
    - darksidewalletd
    - sync performance benchmark tools
    - network interruption tools

**Comment by juanky201271** [comment]
> what do you think about adding to 'whats new' some points:
> 
>     * increased test coverage
> 
>     * upgraded test framework including:
>       
>       * darksidewalletd
>       * sync performance benchmark tools
>       * network interruption tools

I'm happy to do that, there are 4 places with this info:
* this PR
* the tag/release page in github, when I create it.
* in Google Play.
* in Apple Store.

in the four places?

**Comment by Oscar-Pepper** [comment]
> > what do you think about adding to 'whats new' some points:
> > ```
> > * increased test coverage
> > 
> > * upgraded test framework including:
> >   
> >   * darksidewalletd
> >   * sync performance benchmark tools
> >   * network interruption tools
> > ```
> 
> I'm happy to do that, there are 4 places with this info:
> 
> * this PR
> * the tag/release page in github, when I create it.
> * in Google Play.
> * in Apple Store.
> 
> in the four places?

i would say "significant increase in test coverage" actually

**Review by Oscar-Pepper — APPROVED** [review]
Lovely job

**Pull request merged**
