### PR TITLE
First screen with errors in basic mode

### PR DESCRIPTION
**Pull request by juanky201271**
When the App starts you can have an error opening your current wallet... there are many reasons for that, but the App can detect two scenarios:
* Error because no internet connection.
* Error opening the wallet (server / zingolib / zcashd....).

No internet connection (both modes, basic & expert):
Screenshot_20230704_183240

Error opening the wallet (basic mode):
Screenshot_20230704_183058

Error opening the wallet (expert mode):
Screenshot_20230704_183015

@AloeareV @Oscar-Pepper @zancas @fluidvanadium 
Please guys, tell me everything, I'm sure the messages can be improve, with more explanations...)

### CODE REVIEW

**Comment by AloeareV** [comment]
I'm not sure what error cases "Error opening the wallet" represents, if one of them is that it can't connect to the server, could "can't connect to server" have a different screen from "bad/corrupt wallet file"? All the other error messages are clear to me!

**Comment by fluidvanadium** [comment]
maybe in basic mode, it should just create a new wallet?

**Comment by juanky201271** [comment]
> I'm not sure what error cases "Error opening the wallet" represents, if one of them is that it can't connect to the server, could "can't connect to server" have a different screen from "bad/corrupt wallet file"? All the other error messages are clear to me!

I would be happy if I have a list of the errors that I can get when I try to open a wallet file, this way I can do a screen for each one... The only thing I know about the errors are that they start by `Error:`...

**Comment by juanky201271** [comment]
> maybe in basic mode, it should just create a new wallet?

Yes, of course... but when you start the App a second time (the new wallet was created in the first time) then you have a wallet file, and the App have to open this wallet inside of the device... and, here are the possible errors that I'm talking about...

**Comment by juanky201271** [comment]
@fluidvanadium even the App can give you an error when it is trying to create a new wallet... and I need to manage that as well.

**Review by fluidvanadium — DISMISSED** [review]

**Comment by juanky201271** [comment]
@fluidvanadium I did a little change with a new commit, can you approve again, thanks in advance.

**Review by Oscar-Pepper — APPROVED** [review]
looks good. i couldn't get my emulator to trigger the "No internet connection" error (the first image in the PR conversation) but i think this is due to emulator and removing internet from my PC not being the same as actual mobile device ...

**Pull request merged**
