### PR TITLE
Financial Insight

### PR DESCRIPTION
**Pull request by juanky201271**
Working progress...

### CODE REVIEW

**Review by fluidvanadium — COMMENTED** [review]
wow, this is excellent! dry, based and powerful

**Comment by juanky201271** [comment]
This is basic, maybe too basic. But this is a good start. 
@fluidvanadium @zancas @AloeareV @Oscar-Pepper 

If you guys can test it, would be fantastic. I know we want to be simple with this... please tell me your impressions, thanks in advance.

IDEA: maybe the number of transactions per address can be an useful data, I don't know.

**Comment by juanky201271** [comment]
I added in this screen the same logic from this PR: #274 for the scrolling bar.

**Comment by juanky201271** [comment]
ready for review.

**Review by fluidvanadium — APPROVED** [review]

**Pull request merged**
