### PR TITLE
Keyboard animation problems

### LINKED ISSUE #308: Keyboard doesn't close quickly/white background
When you open the keyboard inside the application you can see a white background (below the keyboard), if you change servers to a custom one or Restore a wallet, the keyboard is not hidden quickly.

"Certain processes are heavier and block the user interface, ...and the screen is not recomposed without the keyboard."

https://user-images.githubusercontent.com/37910384/234999250-b33a633e-1d36-458b-a667-68d62f40b788.mp4

### PR DESCRIPTION
**Pull request by juanky201271**
I prevented that the screen become weird when you click on a button with the keyboard open. The App is waiting for a bit while the keyboard animation is finishing.

I rebuild the logic of the checking server function, making a `race` between the RPC calls & a fake process that take 30 seconds to finish, this way I can stop the function after 30 seconds & give a proper toast to the user.

### CODE REVIEW

**Comment by fluidvanadium** [comment]
doesnt seem wrong. testing

**Comment by juanky201271** [comment]
> doesnt seem wrong. testing

how was the testing??? any luck?

**Comment by juanky201271** [comment]
two days later, something new here?

**Comment by fluidvanadium** [comment]
im mainly focusing on improving my tools for emulating and opening the app

**Review by fluidvanadium — APPROVED** [review]
this works!

**Pull request merged**
