### PR TITLE
Suggestion about removing mid-batch saved

### PR DESCRIPTION
**Pull request by juanky201271**
@AloeareV idea. I think the mid-batch saving is a risk more than a benefit.

### CODE REVIEW

**Review by zancas — APPROVED** [review]

**Comment by zancas** [comment]
Did we test this against the sapling balance bug scenario?  What was the result?

**Comment by juanky201271** [comment]
> Did we test this against the sapling balance bug scenario? What was the result?

I'm going to build the APK's with the last dev zingolib commit: `c008e3f` and send to edickson to check it out. Tell me if you have another idea in this matter.

**Comment by zancas** [comment]
There's a plausible hypothesis that the Sapling Excess Balance bug is a save-reload issue.
We should incrementally remove more calls to save, and submit each new APK with a reduced number of save calls, to @Edicksonjga .

So the first APK which is about to be submitted will remove the mid-batch save.

 Is there another save that's not critical?
If there are more non-critical saves:

We should submit should more APKs that each remove another in-essential save.

**Comment by juanky201271** [comment]
These are the `save` moments in the App:
- In Background syncing, every batch synced.
- When the user change some wallet blockchain option, like download_memos.
- When the sync_ID change suddenly in the middle of a sync process. Weird but possible.
- When the sync process finish.
- When the sync process finish a batch or a group of batches (The App check it out every 5 seconds)

It seems like these moments are needed... but I'm open a suggestions.

**Review by AloeareV — APPROVED** [review]

**Comment by juanky201271** [comment]
waiting for CI...

**Comment by zancas** [comment]
Does this no longer need to merge?

**Comment by juanky201271** [comment]
> Does this no longer need to merge?

oh, yes... I was re-running the CI over and over... but I will merge soon.

**Pull request merged**
