### PR TITLE
transparent labels fixed

### PR DESCRIPTION
**Pull request by juanky201271**
We have in same labels something like this: `T-Transparent`, and make not sense, I changed it for `Transparent`.

I realized in translations JSON object we still have a section for `Legacy`, I'm going to remove it right away.

Actually I did already.

### CODE REVIEW

**Comment by fluidvanadium** [comment]
testing

**Comment by juanky201271** [comment]
@fluidvanadium How was the testing????

**Comment by fluidvanadium** [comment]
i got a new test failure.

Screenshot from 2023-03-17 20-20-05

**Comment by juanky201271** [comment]
> i got a new test failure.
> 
> Screenshot from 2023-03-17 20-20-05

If I remember well, this test is for testing the synchronization of a single block in a specific wallet... this failure IMO is not related with this PR, maybe you can open an Issue and we can look into this in another moment.

**Review by fluidvanadium — CHANGES_REQUESTED** [review]
the test failure may be related to changing some details of e2e tests. 

those changes would conflict with how ive updated the e2e tests

will you leave e2e the same for this PR?

**Comment by juanky201271** [comment]
> the test failure may be related to changing some details of e2e tests.
> 
> those changes would conflict with how ive updated the e2e tests
> 
> will you leave e2e the same for this PR?

I think I'm done!!!!! hopefully I removed all of the mistakes that the command: `yarn lint --fix` put in your code in e2e folder. I'm going to exclude this folder of the `lint` scope.

**Comment by fluidvanadium** [comment]
strange, i get the error again. it's only on this branch

**Review by fluidvanadium — APPROVED** [review]
simply changing from (sync_timeout) to (1000000) fixed that error. perhaps something you changed caused my variable name to be overused and wiped? i will investigate. for now, this is okay

**Comment by juanky201271** [comment]
> simply changing from (sync_timeout) to (1000000) fixed that error. perhaps something you changed caused my variable name to be overused and wiped? i will investigate. for now, this is okay

@zancas Maybe if the `lint` checker include errors in the test code -> Let's remove it, right?

**Pull request merged**
