### PR TITLE
File sapling params output & spend removed

### PR DESCRIPTION
**Pull request by juanky201271**
Both repos, zingolib & zingo-mobile have the same files duplicated. I think it is better idea to remove them from zingo-mobile and relies in zingolib's files. In fact for zingo-mobile is a really improvement in same operations like:

* create a new wallet
* open exiting wallet
* restore wallet form seed

In my first test, with a wallet inside of the emulator... I got a weird error from rust lib (unwrap error). It seems like the App problem to open the wallet file from the internal storage, I don't really know the reason, honestly.

When I uninstalled the App and start it again everything is working perfectly.

@AloeareV Please test it carefully with an existing wallet in the emulator, and probably you will get the error above. Would be fantastic if you can figure out this error, maybe is related with the changes I made in the 3 layers of rust in the App.

Please review the `rust` changes... I'm nor reliable in rust, because I have no idea.

### CODE REVIEW

**Comment by juanky201271** [comment]
> Both repos, zingolib & zingo-mobile have the same files duplicated. I think it is better idea to remove them from zingo-mobile and relies in zingolib's files. In fact for zingo-mobile is a really improvement in same operations like:
> 
>     * create a new wallet
> 
>     * open exiting wallet
> 
>     * restore wallet form seed
> 
> 
> In my first test, with a wallet inside of the emulator... I got a weird error from rust lib (unwrap error). It seems like the App problem to open the wallet file from the internal storage, I don't really know the reason, honestly.
> 
> When I uninstalled the App and start it again everything is working perfectly.
> 
> @AloeareV Please test it carefully with an existing wallet in the emulator, and probably you will get the error above. Would be fantastic if you can figure out this error, maybe is related with the changes I made in the 3 layers of rust in the App.
> 
> Please review the `rust` changes... I'm nor reliable in rust, because I have no idea.

In fact my error in my test is the same of those in Google Play... this means that maybe this error is not related with this PR... https://github.com/zingolabs/zingo-mobile/issues/233

**Comment by zancas** [comment]
I think @fluidvanadium should review and test this.

**Comment by fluidvanadium** [comment]
testing

**Review by fluidvanadium — COMMENTED** [review]
a test is failing like this: `23:33:43.561 detox[914046] i new_checkbox_send.test.js is assigned to em
ulator-12512 (30_ga_64)
23:33:47.965 detox[914046] i Example: loads a test wallet
23:33:56.557 detox[914046] i Example: loads a test wallet [OK]
23:33:56.558 detox[914046] i Example: Checkbox send screen -> include UA
 in memo field
23:34:04.943 detox[914046] i Text: undefined
23:34:04.962 detox[914046] i Example: Checkbox send screen -> include UA
 in memo field [FAIL]

 FAIL  e2e/new_checkbox_send.test.js (28.871 s)
  Example
    ✓ loads a test wallet (8592 ms)
    ✕ Checkbox send screen -> include UA in memo field (8404 ms)

  ● Example › Checkbox send screen -> include UA in memo field

    Test Failed: '(view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() covers at least <75> percent of the view's area)' doesn't match the selected view.
    Expected: (view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() covers at least <75> percent of the view's area)
         Got: view was <56> percent visible to the user
    View Details: ReactTextView{id=749, visibility=VISIBLE, width=1028, height=407, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.view.ViewGroup$LayoutParams@ba898af, tag=send.confirm-memo, root-is-layout-requested=false, has-input-connection=false, x=26.0, y=1118.0, text=Reply to:
    u1lx7nlnqqqs7p4hcqz4hyjgnw7h8zskcgr2f8dfhm96np0gnfdzu7jtms7q2pxd7ufy96wxzdsdy65jvp3td7fj2ltcz0jpak86ddyszl9ykn5s86q3xataya5867z3tj2x8cw0ljyrenymr2gcqmjf50gmexqj233yn3kdaxn2yukwcx87emurufakf82wapgnu5h3fvae6aw9uus2r, input-type=0, ime-target=false, has-links=false}

      20 |     log.info('Text:', memo.text);
      21 |
    > 22 |     await expect(memo).toBeVisible();
         |                        ^
      23 |     await expect(memo).toHaveText(
      24 |       'Reply to: \nu1lx7nlnqqqs7p4hcqz4hyjgnw7h8zskcgr2f8dfhm96np0gnfdzu7jtms7q2pxd7ufy96wxzdsdy65jvp3td7fj2ltcz0jpak86ddyszl9ykn5s86q3xataya5867z3tj2x8cw0ljyrenymr2gcqmjf50gmexqj233yn3kdaxn2yukwcx87emurufakf82wapgnu5h3fvae6aw9uus2r',
      25 |     );

      at Object.toBeVisible (e2e/new_checkbox_send.test.js:22:24)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)`
      
the strangest image appears in the emulator:
Screenshot from 2023-03-07 01-44-55

**Comment by juanky201271** [comment]
> a test is failing like this: `23:33:43.561 detox[914046] i new_checkbox_send.test.js is assigned to em ulator-12512 (30_ga_64) 23:33:47.965 detox[914046] i Example: loads a test wallet 23:33:56.557 detox[914046] i Example: loads a test wallet [OK] 23:33:56.558 detox[914046] i Example: Checkbox send screen -> include UA in memo field 23:34:04.943 detox[914046] i Text: undefined 23:34:04.962 detox[914046] i Example: Checkbox send screen -> include UA in memo field [FAIL]
> 
> FAIL e2e/new_checkbox_send.test.js (28.871 s) Example ✓ loads a test wallet (8592 ms) ✕ Checkbox send screen -> include UA in memo field (8404 ms)
> 
> ● Example › Checkbox send screen -> include UA in memo field
> 
> ```
> Test Failed: '(view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() covers at least <75> percent of the view's area)' doesn't match the selected view.
> Expected: (view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() covers at least <75> percent of the view's area)
>      Got: view was <56> percent visible to the user
> View Details: ReactTextView{id=749, visibility=VISIBLE, width=1028, height=407, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.view.ViewGroup$LayoutParams@ba898af, tag=send.confirm-memo, root-is-layout-requested=false, has-input-connection=false, x=26.0, y=1118.0, text=Reply to:
> u1lx7nlnqqqs7p4hcqz4hyjgnw7h8zskcgr2f8dfhm96np0gnfdzu7jtms7q2pxd7ufy96wxzdsdy65jvp3td7fj2ltcz0jpak86ddyszl9ykn5s86q3xataya5867z3tj2x8cw0ljyrenymr2gcqmjf50gmexqj233yn3kdaxn2yukwcx87emurufakf82wapgnu5h3fvae6aw9uus2r, input-type=0, ime-target=false, has-links=false}
> 
>   20 |     log.info('Text:', memo.text);
>   21 |
> > 22 |     await expect(memo).toBeVisible();
>      |                        ^
>   23 |     await expect(memo).toHaveText(
>   24 |       'Reply to: \nu1lx7nlnqqqs7p4hcqz4hyjgnw7h8zskcgr2f8dfhm96np0gnfdzu7jtms7q2pxd7ufy96wxzdsdy65jvp3td7fj2ltcz0jpak86ddyszl9ykn5s86q3xataya5867z3tj2x8cw0ljyrenymr2gcqmjf50gmexqj233yn3kdaxn2yukwcx87emurufakf82wapgnu5h3fvae6aw9uus2r',
>   25 |     );
> 
>   at Object.toBeVisible (e2e/new_checkbox_send.test.js:22:24)
>   at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
>   at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)`
> ```
> 
> the strangest image appears in the emulator: Screenshot from 2023-03-07 01-44-55

Well, I have no idea, this is so weird...

This is my e2e test result:

C:\Users\juank\github\zingo-mobile-juanky\android>yarn detox test -c android.emu.debug
yarn run v1.22.15
$ C:\Users\juank\github\zingo-mobile-juanky\node_modules\.bin\detox test -c android.emu.debug
19:38:08.498 detox[69376] B jest --config e2e/jest.config.js
19:38:56.229 detox[36656] i new_checkbox_send.test.js is assigned to emulator-15666 (Pixel_6_API_30_1)
19:40:23.949 detox[36656] i Example: loads a test wallet
19:40:34.395 detox[36656] i Example: loads a test wallet [OK]
19:40:34.397 detox[36656] i Example: Checkbox send screen -> include UA in memo field
19:40:46.815 detox[36656] i Text: undefined
19:40:46.842 detox[36656] i Example: Checkbox send screen -> include UA in memo field [OK]

 PASS  e2e/new_checkbox_send.test.js (157.082 s)
  Example
    √ loads a test wallet (10446 ms)
    √ Checkbox send screen -> include UA in memo field (12444 ms)

19:41:00.119 detox[36656] i 03_new_wallet.test.js is assigned to emulator-15666 (Pixel_6_API_30_1)
19:41:08.701 detox[36656] i Example: New wallet button works
19:41:18.177 detox[36656] i
19:41:18.178 detox[36656] i Value: undefined
19:41:18.178 detox[36656] i Text: History
19:41:18.179 detox[36656] i Visibility: visible
19:41:18.179 detox[36656] i Width (pixels): 180
19:41:18.209 detox[36656] i Example: New wallet button works [OK]

 PASS  e2e/03_new_wallet.test.js (31.287 s)
  Example
    √ New wallet button works (9508 ms)

19:41:29.003 detox[36656] i 02_preexisting.test.js is assigned to emulator-15666 (Pixel_6_API_30_1)
19:41:36.714 detox[36656] i Renders wallet data correctly.: loads my test wallet
19:41:47.061 detox[36656] i Renders wallet data correctly.: loads my test wallet [OK]
19:41:47.063 detox[36656] i Renders wallet data correctly.: synks 1 block and renders a transaction. this should take less than a minute, but will time out after 16 minutes
19:42:00.259 detox[36656] i The app seems to be idle
19:42:10.264 detox[36656] i The app seems to be idle
19:42:19.653 detox[36656] i Renders wallet data correctly.: synks 1 block and renders a transaction. this should take less than a minute, but will time out after 16 minutes [OK]
19:42:19.654 detox[36656] i Renders wallet data correctly.: renders correct addresses
19:42:23.119 detox[36656] i Renders wallet data correctly.: renders correct addresses [OK]

 PASS  e2e/02_preexisting.test.js (64.852 s)
  Renders wallet data correctly.
    √ loads my test wallet (10348 ms)
    √ synks 1 block and renders a transaction. this should take less than a minute, but will time out after 16 minutes (32590 ms)
    √ renders correct addresses (3464 ms)

Done in 255.37s.

No problem at all...

**Comment by juanky201271** [comment]
@fluidvanadium just an idea... run `yarn install` before, Just in case... and you have to re-build the `rust` libs. (probably you did this already).

**Comment by fluidvanadium** [comment]
error only happens on 
`yarn detox test new_checkbox_send -c android.emu.32`
created by
`avdmanager create avd --force --name 30_ga_64 --package 'system-images;android-30;google_apis;x86_64' -d pixel_6 --skin pixel_6`

**Comment by fluidvanadium** [comment]
okay, that little guy is the emulator camera
detox must be accidently hitting the scan button, which causes an error by being off the screen. not related to this PR

**Review by fluidvanadium — DISMISSED** [review]
see comment thread

**Comment by Oscar-Pepper** [comment]
@juanky201271  your commits aren't signed ??

**Comment by juanky201271** [comment]
> @juanky201271 your commits aren't signed ??

Yes, It's annoying... this happens when you `rebase` using the button in this github page... last time I do this.

**Comment by juanky201271** [comment]
@fluidvanadium I rebase this branch & I have the commits all signed... It's a beauty. Can you, please, approve again this PR. Thanks a lot in advance.

**Review by fluidvanadium — DISMISSED** [review]
is good

**Comment by juanky201271** [comment]
> is good

@fluidvanadium I'm sorry but I need it again... because meanwhile another PR was merged, and I had to rebase again too... this is really fun... :D

**Review by fluidvanadium — APPROVED** [review]
Same thing happened to me last week.

**Pull request merged**
