### PR TITLE
command line integ tests for multiple architectures

### PR DESCRIPTION
**Pull request by Oscar-Pepper**

### CODE REVIEW

**Comment by Oscar-Pepper** [comment]
run from `zingo-mobile/android`:
./gradlew allArchsGroupDebugAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=org.ZingoLabs.Zingo.IntegrationTestSuite

**Review by juanky201271 — DISMISSED** [review]
I just execute the command and works.

**Comment by fluidvanadium** [comment]
hmm, i get the following error

```1678984064 || sava (HEAD detached at oscar/multi_device_integration_tests)[ ]
/home/sava/ZINGO/nzingo-mobile/android: 0 $
./gradlew allArchsGroupDebugAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=org.ZingoLabs.Zingo.IntegrationTestSuite

> Configure project :app
WARNING: The Gradle Managed Device DSL and associated tests are experimental

> Configure project :react-native-reanimated
AAR for react-native-reanimated has been found
/home/sava/ZINGO/nzingo-mobile/node_modules/react-native-reanimated/android/react-native-reanimated-70-hermes.aar

> Task :app:pixel2api29_x86Setup
Checking the license for package Intel x86 Atom System Image in /home/sava/Android/Sdk/licenses
License for package Intel x86 Atom System Image accepted.
Preparing "Install Intel x86 Atom System Image (revision: 8)".

> Task :app:stripDebugDebugSymbols
Unable to strip the following libraries, packaging them as they are: librust.so.

> Task :app:pixel2api30_x86_64Setup
Checking the license for package Intel x86_64 Atom System Image in /home/sava/Android/Sdk/licenses
License for package Intel x86_64 Atom System Image accepted.
Preparing "Install Intel x86_64 Atom System Image (revision: 10)".

> Task :app:pixel2api29_x86Setup
"Install Intel x86 Atom System Image (revision: 8)" ready.
Installing Intel x86 Atom System Image in /home/sava/Android/Sdk/system-images/android-29/default/x86
"Install Intel x86 Atom System Image (revision: 8)" complete.
"Install Intel x86 Atom System Image (revision: 8)" finished.
Failed to to retrieve system image at: /home/sava/Android/Sdk/system-images/android-29/default/x86 Retrying in 2 seconds
Failed to to retrieve system image at: /home/sava/Android/Sdk/system-images/android-29/default/x86 Retrying in 4 seconds

> Task :app:pixel2api30_x86_64Setup
"Install Intel x86_64 Atom System Image (revision: 10)" ready.
Installing Intel x86_64 Atom System Image in /home/sava/Android/Sdk/system-images/android-30/default/x86_64
"Install Intel x86_64 Atom System Image (revision: 10)" complete.
"Install Intel x86_64 Atom System Image (revision: 10)" finished.
Failed to to retrieve system image at: /home/sava/Android/Sdk/system-images/android-30/default/x86_64 Retrying in 2 seconds
Failed to to retrieve system image at: /home/sava/Android/Sdk/system-images/android-30/default/x86_64 Retrying in 4 seconds
Failed to to retrieve system image at: /home/sava/Android/Sdk/system-images/android-30/default/x86_64 Retrying in 8 seconds
Failed to to retrieve system image at: /home/sava/Android/Sdk/system-images/android-30/default/x86_64 Retrying in 10 seconds

> Task :app:pixel2api29_x86Setup FAILED
Failed to to retrieve system image at: /home/sava/Android/Sdk/system-images/android-29/default/x86 Retrying in 8 seconds
Failed to to retrieve system image at: /home/sava/Android/Sdk/system-images/android-29/default/x86 Retrying in 10 seconds

> Task :app:pixel2api30_x86_64Setup FAILED

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:pixel2api29_x86Setup'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.ManagedDeviceSetupTask$ManagedDeviceSetupRunnable
   > System image does not exist at /home/sava/Android/Sdk/system-images/android-29/default/x86

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:pixel2api30_x86_64Setup'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.ManagedDeviceSetupTask$ManagedDeviceSetupRunnable
   > System image does not exist at /home/sava/Android/Sdk/system-images/android-30/default/x86_64

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 21s
314 actionable tasks: 8 executed, 306 up-to-date```

**Comment by Oscar-Pepper** [comment]
ok to run without opening emulator:
`./gradlew x86_ArchsGroupDebugAndroidTest -Pandroid.testoptions.manageddevices.emulator.gpu=swiftshader_indirect -Pandroid.testInstrumentationRunnerArguments.class=org.ZingoLabs.Zingo.IntegrationTestSuite`

**Comment by juanky201271** [comment]
this is my output... (the test were running)

C:\Users\juank\github\zingo-mobile-oscar\android>gradlew.bat x86_ArchsGroupDebugAndroidTest -Pandroid.testoptions.manageddevices.emulator.gpu=swiftshader_indirect -Pandroid.testInstrumentationRunnerArguments.class=org.ZingoLabs.Zingo.IntegrationTestSuite
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Configure project :app
WARNING: The Gradle Managed Device DSL and associated tests are experimental

> Configure project :react-native-reanimated
AAR for react-native-reanimated has been found
C:\Users\juank\github\zingo-mobile-oscar\node_modules\react-native-reanimated\android\react-native-reanimated-70-hermes.aar

> Task :app:pixel2api30_x86_64DebugAndroidTest
Starting 1 tests on pixel2api30_x86_64

> Task :app:mergeDebugAndroidTestTestResultProtos

Test results saved as file:/C:/Users/juank/github/zingo-mobile-oscar/android/app/build/outputs/androidTest-results/managedDevice/test-result.pb
Inspect these results in Android Studio by selecting Run > Import Tests From File from the menu bar and importing test-result.pb.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1m 35s
317 actionable tasks: 6 executed, 311 up-to-date

**Comment by Oscar-Pepper** [comment]
> this is my output... (the test were running)
> 
> C:\Users\juank\github\zingo-mobile-oscar\android>gradlew.bat x86_ArchsGroupDebugAndroidTest -Pandroid.testoptions.manageddevices.emulator.gpu=swiftshader_indirect -Pandroid.testInstrumentationRunnerArguments.class=org.ZingoLabs.Zingo.IntegrationTestSuite Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
> 
> > Configure project :app
> > WARNING: The Gradle Managed Device DSL and associated tests are experimental
> 
> > Configure project :react-native-reanimated
> > AAR for react-native-reanimated has been found
> > C:\Users\juank\github\zingo-mobile-oscar\node_modules\react-native-reanimated\android\react-native-reanimated-70-hermes.aar
> 
> > Task :app:pixel2api30_x86_64DebugAndroidTest
> > Starting 1 tests on pixel2api30_x86_64
> 
> > Task :app:mergeDebugAndroidTestTestResultProtos
> 
> Test results saved as file:/C:/Users/juank/github/zingo-mobile-oscar/android/app/build/outputs/androidTest-results/managedDevice/test-result.pb Inspect these results in Android Studio by selecting Run > Import Tests From File from the menu bar and importing test-result.pb.
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
> 
> You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
> 
> See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
> 
> BUILD SUCCESSFUL in 1m 35s 317 actionable tasks: 6 executed, 311 up-to-date

It only tested x86_64? maybe x86 was cached? Ive updated readme so ready for merge if you approve

**Review by juanky201271 — APPROVED** [review]
I don't see any problem here. Great job.

**Pull request merged**
